# ci.yml
name: next-blog-front

on:
    push:
        branches: 
          - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy
              uses: matheusvanzan/sshpass-action@v2
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  user: 'root'
                  port: 22
                  pass: ${{ secrets.REMOTE_PASSWORD }}
                  run: | 
                    cd /root/next/next-blog-front
                    pm2 kill
                    git pull origin
                    npm run build
                    npm run pm2-start
                    pwd
                    exit
