# ci.yml
name: next-blog-front

on:
    push:
        branches: 
          - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
                
            - name: Deploy
              uses: matheusvanzan/sshpass-action@v2
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  user: 'root'
                  port: 22
                  pass: ${{ secrets.REMOTE_PASSWORD }}
                  run: | 
                    cd /root/next/next-blog-front
                    export PATH=$PATH:/usr/local/nodejs/bin
                    /usr/local/nodejs/bin/pm2 kill
                    git pull origin
                    /usr/local/nodejs/bin/npm run install
                    /usr/local/nodejs/bin/npm run build
                    /usr/local/nodejs/bin/npm run pm2-start
                    pwd
                    exit
